### ISSUE TITLE
Inline/external plots

### ISSUE THREAD

**Issue by profgerto** [imatlab/imatlab#27]
Hi,

I'm using the iMatlab kernel with Python 3.5.4. and Matlab 2017a. I'm having trouble getting matlab to plot inline. When using the old Calysto kernel, it automatically plotted inline, but with the new iMatlab kernel it opens a separate Matlab windows. How can I switch between inline and external plots?

My apologies if this is the wrong place for asking, but I couldnt find any other place.

**Comment by anntzer** [comment]
Does https://github.com/imatlab/imatlab#inline-graphics help?

**Comment by profgerto** [comment]
I tried, but that didn't work for me the first couple of times. But as I understood, this uses plotly. Is it possible to simply use the matlab plotter?

**Comment by anntzer** [comment]
Yes.  Sorry this is poorly documented indeed (it looks like everyone moved to using plotly so I forgot about it...).  Please first call `imatlab_export_fig('print-png')` before creating any plot.  This can be done in the notebook, or in your startup.m (in that later case you may need to wrap the thing in a try.. catch because `imatlab_export_fig` will by default be in your path only when running the jupyter kernel).

**Comment by profgerto** [comment]
This works, thank you. It does up quickly in a matlab window before closing though. Do you know how to fix that?

**Comment by anntzer** [comment]
Should be fixed as of master now.

**Comment by profgerto** [comment]
Great, thanks!
